-- ============================================
-- PUNCHME MERCHANT PORTAL AUTHENTICATION
-- Add these tables to your existing database
-- ============================================

-- 1. Merchant Portal Users (for authentication)
CREATE TABLE IF NOT EXISTS merchant_portal_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id UUID REFERENCES merchants(id) ON DELETE CASCADE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'owner' CHECK (role IN ('owner', 'manager', 'viewer')),
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Dashboard Preferences (optional but nice to have)
CREATE TABLE IF NOT EXISTS merchant_dashboard_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id UUID REFERENCES merchants(id) ON DELETE CASCADE UNIQUE NOT NULL,
  default_date_range TEXT DEFAULT '30days' CHECK (default_date_range IN ('7days', '30days', '90days', 'custom')),
  favorite_metrics JSONB DEFAULT '["activeCards", "totalRewards", "stampActivity"]'::jsonb,
  email_notifications BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Login Sessions (track active sessions)
CREATE TABLE IF NOT EXISTS merchant_portal_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES merchant_portal_users(id) ON DELETE CASCADE NOT NULL,
  merchant_id UUID REFERENCES merchants(id) ON DELETE CASCADE NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- Ensures merchants can ONLY see their own data
-- ============================================

-- Enable RLS on merchant portal tables
ALTER TABLE merchant_portal_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_portal_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_dashboard_preferences ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Merchants can only see their own portal user record
CREATE POLICY merchant_portal_users_select 
  ON merchant_portal_users 
  FOR SELECT 
  USING (auth.uid() = id OR merchant_id = (
    SELECT merchant_id FROM merchant_portal_sessions 
    WHERE token = current_setting('request.jwt.claims', true)::json->>'session_token'
  ));

-- RLS Policy: Merchants can only see their own sessions
CREATE POLICY merchant_portal_sessions_select 
  ON merchant_portal_sessions 
  FOR SELECT 
  USING (user_id = auth.uid());

-- RLS Policy: Merchants can only see their own preferences
CREATE POLICY merchant_dashboard_preferences_select 
  ON merchant_dashboard_preferences 
  FOR SELECT 
  USING (merchant_id = (
    SELECT merchant_id FROM merchant_portal_sessions 
    WHERE token = current_setting('request.jwt.claims', true)::json->>'session_token'
  ));

-- ============================================
-- INDEXES (for better performance)
-- ============================================

CREATE INDEX idx_merchant_portal_users_merchant_id ON merchant_portal_users(merchant_id);
CREATE INDEX idx_merchant_portal_users_email ON merchant_portal_users(email);
CREATE INDEX idx_merchant_portal_sessions_token ON merchant_portal_sessions(token);
CREATE INDEX idx_merchant_portal_sessions_merchant_id ON merchant_portal_sessions(merchant_id);
CREATE INDEX idx_merchant_portal_sessions_expires_at ON merchant_portal_sessions(expires_at);

-- ============================================
-- HELPER FUNCTION: Clean up expired sessions
-- ============================================

CREATE OR REPLACE FUNCTION cleanup_expired_sessions()
RETURNS void AS $$
BEGIN
  DELETE FROM merchant_portal_sessions WHERE expires_at < now();
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- SAMPLE DATA: Create a test merchant user
-- ============================================

-- Example: Create a user for "Brew & Bean" merchant
-- Password: "password123" (hashed with bcrypt)
-- You'll need to update this with a real bcrypt hash

INSERT INTO merchant_portal_users (merchant_id, email, password_hash, full_name, role)
SELECT 
  id,
  'admin@brewandbean.com',
  '$2a$10$rZ5yL5wZ5yL5wZ5yL5wZ5Om5yL5wZ5yL5wZ5yL5wZ5yL5wZ5yL5w', -- This is a placeholder hash
  'Brew & Bean Admin',
  'owner'
FROM merchants 
WHERE name = 'Brew & Bean'
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- NOTES:
-- ============================================
-- 1. Run this in Supabase SQL Editor
-- 2. Update password_hash with real bcrypt hashes
-- 3. The RLS policies ensure data isolation between merchants
-- 4. Session tokens will be generated by your backend
